#!/bin/bash

set -e

echo "---"
echo "bosh_root_storage_account: $(terraform output bosh_root_storage_account)"
echo "client_id: $(terraform output client_id)"
echo "client_secret: $(terraform output client_secret)"
echo "wildcard_vm_storage_account: '$(terraform output wildcard_vm_storage_account)'"
echo "bosh_deployed_vms_security_group_name: $(terraform output bosh_deployed_vms_security_group_name)"
echo "pcf_resource_group_name: $(terraform output pcf_resource_group_name)"
echo "subscription_id: $(terraform output subscription_id)"
echo "tenant_id: $(terraform output tenant_id)"
echo "network_name: $(terraform output network_name)"
echo "network_resource_group_name: $(terraform output network_resource_group_name)"
echo "infrastructure_subnet_name: $(terraform output infrastructure_subnet_name)"
echo "infrastructure_subnet_cidrs: $(terraform output infrastructure_subnet_cidrs)"
echo "infrastructure_subnet_gateway: $(terraform output infrastructure_subnet_gateway)"
echo "infrastructure_subnet_reserved_range: $(terraform output infrastructure_subnet_reserved_range)"
echo "pas_subnet_name: $(terraform output pas_subnet_name)"
echo "pas_subnet_cidrs: $(terraform output pas_subnet_cidrs)"
echo "pas_subnet_gateway: $(terraform output pas_subnet_gateway)"
echo "pas_subnet_reserved_range: $(terraform output pas_subnet_reserved_range)"
echo "services_subnet_name: $(terraform output services_subnet_name)"
echo "services_subnet_cidrs: $(terraform output services_subnet_cidrs)  "
echo "services_subnet_gateway: $(terraform output services_subnet_gateway)"
echo "services_subnet_reserved_range: $(terraform output services_subnet_reserved_range)"
echo "ops_manager_ssh_public_key: $(terraform output ops_manager_ssh_public_key)"
echo "ops_manager_ssh_private_key: |-"
echo "$(terraform output ops_manager_ssh_private_key | awk '{print " ", $0}')"
