product-name: pivotal-mysql
product-properties:
  .properties.allow_lower_case_table_names_via_config_param:
    value: false
  .properties.audit_logging_enabled:
    value: false
  .properties.backups_selector:
    value: Azure Backups
  .properties.canary_instances:
    value: 0
  .properties.enable_lower_case_table_names:
    value: false
  .properties.enable_read_only_admin:
    value: false
  .properties.enable_secure_binding_credentials:
    value: false
  .properties.enable_tls_selector:
    value: disabled
  .properties.global_service_instance_limit:
    value: 50
  .properties.local_infile:
    value: false
  .properties.mysql_metrics_frequency:
    value: 30
  .properties.plan1_selector:
    value: Active
  .properties.plan2_selector:
    value: Active
  .properties.plan3_selector:
    value: Active
  .properties.plan4_selector:
    value: Inactive
  .properties.plan5_selector:
    value: Inactive
  .properties.request_timeout:
    value: 120
  .properties.simultaneous_upgrades:
    value: 1
  .properties.syslog_migration_selector:
    value: disabled
  .properties.userstat:
    value: false
network-properties:
  network:
    name: ((network))
  other_availability_zones:
  - name: "null"
  service_network:
    name: ((service_network))
  singleton_availability_zone:
    name: "null"
resource-config:
  dedicated-mysql-broker:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
errand-config:
  delete-all-service-instances-and-deregister-broker:
    pre-delete-state: true
  register-broker:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
  upgrade-all-service-instances:
    post-deploy-state: true
